import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight, Activity, Layers, ShieldCheck, Search, ChevronRight, Check, X, RefreshCw, Send, Radio} from 'lucide-react';
import './style.css';
type Case = {id:string; message:string; customer_id:string; state:string; plan:Record<string,any>; evidence:Record<string,any>; result:Record<string,any>; created_at:string; shadow:boolean};
type Audit = {id:string; timestamp:string; tool_name:string; result:Record<string,any>; arguments:Record<string,any>; error:string|null; latency_ms:number; authorization:string};
const money=(v:number=0)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v/100);
function App(){
 const [token,setToken]=useState(''),[connected,setConnected]=useState(false),[role,setRole]=useState('operator');
 const [cases,setCases]=useState<Case[]>([]),[selected,setSelected]=useState<Case|null>(null),[logs,setLogs]=useState<Audit[]>([]);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[filter,setFilter]=useState('all'),[query,setQuery]=useState('');
 const [message,setMessage]=useState('I cancelled last week but was charged $89. Please refund me.'),[target,setTarget]=useState('pay_demo'),[address,setAddress]=useState('');
 const [amount,setAmount]=useState(''),[note,setNote]=useState(''),[tab,setTab]=useState('evidence');
 async function api(path:string,method='GET',body?:object){
  const r=await fetch('/api'+path,{method,headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
  const data=await r.json();if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;
 }
 async function refresh(){const data=await api('/cases');setCases(data);setConnected(true);if(selected){const c=data.find((x:Case)=>x.id===selected.id);if(c)await choose(c);}}
 async function choose(c:Case){setSelected(c);setLogs(await api('/cases/'+c.id+'/trajectory'));setAmount(String(c.plan.amount_cents??''));}
 async function task(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function decision(d:string){if(!selected)return;await task(async()=>{const c=await api('/cases/'+selected.id+'/decision','POST',{decision:d,note,...(d==='modify'?{amount_cents:Number(amount)}:{})});await refresh();await choose(c);});}
 const waiting=cases.filter(c=>['ESCALATE','CONFIRM'].includes(c.state)).length;
 const resolved=cases.filter(c=>c.state==='RESPOND').length;
 const filtered=cases.filter(c=>(filter==='all'||(filter==='review'?['ESCALATE','CONFIRM'].includes(c.state):c.state==='RESPOND'))&&(c.message+' '+c.id).toLowerCase().includes(query.toLowerCase()));
 return <div className="shell"><aside className="sidebar"><div className="brand"><span className="mark"><Layers size={23}/></span>conduit<span className="dot">.</span></div><div className="workspace">WORKSPACE <span>01</span></div><button className="nav active" onClick={()=>setFilter('all')}><Layers size={18}/> Resolution desk <span>{cases.length}</span></button><button className="nav" onClick={()=>setFilter('review')}><ShieldCheck size={18}/> Awaiting review <span>{waiting}</span></button><div className="sidebar-bottom"><Radio size={16}/><div>Simulation environment<small>Test data · no real money</small></div></div></aside>
 <main><header><div className="breadcrumb">Workspace <ChevronRight size={14}/> Resolution desk</div><div className="live"><i/> {connected?'Connected':'Not connected'} <span className="avatar">KS</span></div></header><div className="page"><div className="heading"><div><div className="eyebrow">HUMAN JUDGMENT, WHERE IT MATTERS</div><h1>Resolution desk</h1><p>Every action has evidence. Every decision leaves a trace.</p></div><button className="secondary" disabled={busy||!connected} onClick={()=>task(refresh)}><RefreshCw size={15}/> Refresh</button></div>
 {!connected?<section className="login"><ShieldCheck size={30}/><h2>Connect to your workspace</h2><p>Enter the customer or operator token from your server configuration. Tokens stay in memory.</p><div className="form-row"><select aria-label="Console role" value={role} onChange={e=>setRole(e.target.value)}><option value="operator">Operator</option><option value="customer">Customer</option></select><input type="password" aria-label="Bearer token" placeholder="Bearer token" value={token} onChange={e=>setToken(e.target.value)}/><button disabled={busy||!token} onClick={()=>task(refresh)}>Connect <ArrowUpRight size={16}/></button></div></section>:<>
 <div className="metrics"><div><span>Total cases</span><strong>{cases.length}<small>in this workspace</small></strong></div><div><span>Awaiting a decision</span><strong>{waiting}<small className="amber">Human oversight</small></strong></div><div><span>Verified resolutions</span><strong>{resolved}<small className="green">{cases.length?Math.round(resolved/cases.length*100):0}% of cases</small></strong></div><div><span>Safety architecture</span><strong className="safety"><ShieldCheck size={24}/> Enforced<small>Policy + authorization</small></strong></div></div>
 {role==='customer'&&<section className="new-case"><h3>Submit a support request</h3><textarea aria-label="Customer request" value={message} onChange={e=>setMessage(e.target.value)}/><div className="form-row"><input aria-label="Target ID" value={target} onChange={e=>setTarget(e.target.value)} placeholder="Payment / subscription / order ID"/><input aria-label="New address" value={address} onChange={e=>setAddress(e.target.value)} placeholder="New address (if needed)"/><button disabled={busy} onClick={()=>task(async()=>{const c=await api('/cases','POST',{message,target_id:target||null,address:address||null,request_key:crypto.randomUUID()});await refresh();await choose(c);})}><Send size={15}/> Submit</button></div></section>}
 <div className="desk"><section className="queue"><div className="section-title"><h2>Case queue</h2><span>{filtered.length} cases</span></div><div className="filters"><button className={filter==='all'?'chosen':''} onClick={()=>setFilter('all')}>All cases</button><button className={filter==='review'?'chosen':''} onClick={()=>setFilter('review')}>Needs review</button><button className={filter==='resolved'?'chosen':''} onClick={()=>setFilter('resolved')}>Resolved</button></div><label className="search"><Search size={16}/><input placeholder="Search cases…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="case-list">{filtered.length===0?<div className="empty"><Layers size={28}/><h3>No cases yet</h3><p>Submit a request using customer access to see its investigation here.</p></div>:filtered.map(c=><button key={c.id} className={'case '+(selected?.id===c.id?'selected':'')} onClick={()=>task(()=>choose(c))}><div className="case-meta"><span>#{c.id.slice(0,8)}</span><span className={'badge '+c.state.toLowerCase()}>{c.state.replaceAll('_',' ')}</span></div><h3>{c.message}</h3><div className="case-foot"><span>{c.customer_id}</span><span>{c.plan.action||'Investigation'} <ChevronRight size={14}/></span></div></button>)}</div></section>
 <section className="detail">{!selected?<div className="empty large"><Activity size={34}/><h2>The full picture, in one place.</h2><p>Select a case to inspect its evidence, policy decision, and execution history.</p></div>:<><div className="detail-top"><div><div className="eyebrow">CASE #{selected.id.slice(0,8)}</div><h2>{selected.plan.action?selected.plan.action[0].toUpperCase()+selected.plan.action.slice(1)+' request':'Investigation'}</h2></div><span className={'badge '+selected.state.toLowerCase()}>{selected.state}</span></div><blockquote>“{selected.message}”</blockquote><div className="tabs"><button className={tab==='evidence'?'chosen':''} onClick={()=>setTab('evidence')}>Evidence & decision</button><button className={tab==='trajectory'?'chosen':''} onClick={()=>setTab('trajectory')}>Trajectory <span>{logs.length}</span></button></div>
 {tab==='evidence'?<div className="evidence"><div className="proposal"><span>PROPOSED ACTION</span><h2>{selected.plan.action||'Awaiting details'} <strong>{selected.plan.amount_cents?money(selected.plan.amount_cents):''}</strong></h2><p>{selected.plan.target_id}</p></div><dl><div><dt>Policy</dt><dd>{selected.evidence.policy?.policy||'Pending'} <small>{selected.evidence.policy?.version}</small></dd></div><div><dt>Required authority</dt><dd>{selected.evidence.authorization||'Pending'}</dd></div><div><dt>Risk score</dt><dd>{selected.evidence.risk?.score??'—'} <small>Uncalibrated heuristic</small></dd></div>{selected.evidence.subscription&&<div><dt>Cancelled at</dt><dd>{selected.evidence.subscription.cancelled_at||'Not cancelled'}</dd></div>}{selected.evidence.payment&&<div><dt>Payment created</dt><dd>{selected.evidence.payment.created_at}</dd></div>}</dl><div className="reason"><ShieldCheck size={18}/><p>{selected.evidence.policy?.explanation||selected.result.message}</p></div><div className="outcome"><b>Current outcome</b><p>{selected.result.message}</p></div>
 {['CONFIRM','ESCALATE'].includes(selected.state)&&<div className="decisions"><textarea aria-label="Decision note" placeholder="Decision note (recorded in the audit log)" value={note} onChange={e=>setNote(e.target.value)}/><div className="form-row"><button disabled={busy||(role==='customer'&&selected.state==='ESCALATE')} onClick={()=>decision('approve')}><Check size={16}/> {role==='customer'?'Confirm':'Approve'}</button><button disabled={busy||(role==='customer'&&selected.state==='ESCALATE')} className="secondary" onClick={()=>decision('reject')}><X size={16}/> Reject</button></div>{role==='operator'&&['refund','credit'].includes(selected.plan.action)&&<div className="form-row modify"><input type="number" min="1" max={selected.plan.amount_cents} aria-label="Reduced amount in cents" value={amount} onChange={e=>setAmount(e.target.value)}/><button disabled={busy} className="secondary" onClick={()=>decision('modify')}>Reduce & approve (cents)</button></div>}</div>}
 {selected.state==='RECONCILE'&&<button disabled={busy} onClick={()=>task(async()=>{const c=await api('/cases/'+selected.id+'/reconcile','POST');await refresh();await choose(c);})}><RefreshCw size={16}/> Reconcile state</button>}
 {selected.state==='ASK_USER'&&role==='customer'&&<button disabled={busy} onClick={()=>task(async()=>{const c=await api('/cases/'+selected.id+'/clarify','POST',{message,target_id:target||null,address:address||null,request_key:crypto.randomUUID()});await refresh();await choose(c);})}>Use request form above to clarify</button>}
 </div>:<div className="timeline">{logs.map(l=><details key={l.id}><summary><span className={'timeline-dot '+(l.error?'bad':'')}/><div><b>{l.tool_name==='state'?l.result.state:l.tool_name}</b><small>{l.error||l.authorization}</small></div><time>{l.latency_ms.toFixed(1)} ms</time></summary><pre>{JSON.stringify({arguments:l.arguments,result:l.result,error:l.error},null,2)}</pre></details>)}</div>}</>}</section></div></>}
 {error&&<div role="alert" className="error">{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}<footer>CONDUIT <span>Deterministic safeguards. Observable outcomes.</span><small>Prototype · simulator / test mode only</small></footer></div></main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
